<?php
/**
 * Copyright © Rob Aimes - https://aimes.dev/
 * https://github.com/robaimes
 */

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
?>
<div>
    <strong>
        <?= $escaper->escapeHtml(__(
            'An update for the <code>%package_name</code> package is available. Additional patches may be available.',
            [
                'package_name' => $block->getName(),
            ]
        ), ['code']); ?>
    </strong>
    <br/>
    <br/>
    <span>
        <?= $escaper->escapeHtml(__(
            'Your current version is <code>%current_version</code> and the latest version available is <code>%latest_version</code>.',
            [
                'current_version' => $block->getCurrentVersion(),
                'latest_version' => $block->getLatest(),
            ]
        ), ['code']); ?>
    </span>
    <br/>
    <a href="<?= $escaper->escapeUrl($block->getReleaseNotesUrl()) ?>" target="_blank" rel="noopener noreferrer">
        <?= $escaper->escapeHtml(__('View release notes')); ?>
    </a>
</div>
